{
 "title": "FastID - Report",
 "time": { "from": "2023-09-17T16:49:59.709Z", "to": "2024-12-14T05:01:43.050Z" },
 "templating": {
  "list": [
   {
    "name": "SelectedClienti",
    "label": "Cliente",
    "query": "SELECT \"Cliente\" FROM \"Clienti\""
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM \"Clienti\""
    }
   ]
  },
  {
   "title": "Transazioni",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(\"Date\", $__interval) as time,\r\n  sum(\"PredictedTransactionsCount\") AS \"Transazioni predette con correzione\"\r\nFROM \"PredictedTransactionsCount\"\r\nWHERE\r\n($SelectedClienti='*' OR\r\n  \"User_Name\"=$SelectedClienti) AND\r\n  \"IsAfterRetrain\" = TRUE AND\r\n$__timeFilter(\"Date\")\r\nGROUP BY time\r\nORDER BY time"
    },
    {
     "rawSql": "SELECT\r\n  $__timeGroup(\"Date\", $__interval) as time,\r\n  sum(\"PredictedTransactionsCount\") AS \"Transazioni predette\"\r\nFROM \"PredictedTransactionsCount\"\r\nWHERE\r\n($SelectedClienti='*' OR\r\n  \"User_Name\"=$SelectedClienti) AND\r\n  \"IsAfterRetrain\" = FALSE AND\r\n$__timeFilter(\"Date\")\r\nGROUP BY time\r\nORDER BY time"
    },
    {
     "rawSql": "SELECT\r\n  $__timeGroup(\"Date\", $__interval) as time,\r\n  sum(\"TransactionsCount\") AS \"Transazioni effettive\"\r\nFROM \"TransactionsCount\"\r\nWHERE\r\n($SelectedClienti='*' OR\r\n  \"User_Name\"=$SelectedClienti) AND\r\n$__timeFilter(\"Date\")\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(\"TransactionsCount\") FROM \"TransactionsCount\""
    }
   ]
  },
  {
   "title": "Prediction error",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(ptc.\"Date\", $__interval),\r\n  AVG(ABS(ptc.\"PredictedTransactionsCount\" - tc.\"TransactionsCount\") / tc.\"TransactionsCount\") AS predicted_increase_perc\r\nFROM \"PredictedTransactionsCount\" ptc\r\nJOIN \"TransactionsCount\" tc ON tc.\"Date\" = ptc.\"Date\" AND tc.\"User_Name\" = ptc.\"User_Name\"\r\nWHERE\r\n($SelectedClienti='*' OR\r\n  ptc.\"User_Name\"=$SelectedClienti) AND\r\n  ptc.\"PredictedTransactionsCount\" != 0 AND\r\n  ptc.\"IsAfterRetrain\" = FALSE AND\r\n$__timeFilter(ptc.\"Date\")\r\nGROUP BY time\r\nORDER BY time desc"
    },
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(ptc.\"Date\", $__interval),\r\n  AVG((ptc.\"PredictedTransactionsCount\" - tc.\"TransactionsCount\") / ABS(tc.\"TransactionsCount\"))  AS predicted_corrected_increase_perc\r\nFROM \"PredictedTransactionsCount\" ptc\r\nJOIN \"TransactionsCount\" tc ON tc.\"Date\" = ptc.\"Date\" AND tc.\"User_Name\" = ptc.\"User_Name\"\r\nWHERE\r\n($SelectedClienti='*' OR\r\n  ptc.\"User_Name\"=$SelectedClienti) AND\r\n  ptc.\"PredictedTransactionsCount\" != 0 AND\r\n  ptc.\"IsAfterRetrain\" = TRUE AND\r\n$__timeFilter(ptc.\"Date\")\r\nGROUP BY time\r\nORDER BY time desc"
    }
   ]
  },
  {
   "title": "R²",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH stats AS (\r\n  SELECT\r\n    \"PredictedTransactionsCount\", \"TransactionsCount\"\r\n  FROM \"PredictedTransactionsCount\" ptc\r\n  JOIN \"TransactionsCount\" tc ON tc.\"User_Name\" = ptc.\"User_Name\" AND tc.\"Date\" = ptc.\"Date\"\r\n  WHERE\r\n  ($SelectedClienti='*' OR\r\n    ptc.\"User_Name\"=$SelectedClienti) AND\r\n    ptc.\"PredictedTransactionsCount\" != 0 AND\r\n    tc.\"TransactionsCount\" != 0 AND\r\n    ptc.\"IsAfterRetrain\" = FALSE AND\r\n  $__timeFilter(ptc.\"Date\")\r\n)\r\nSELECT\r\n  POWER(CORR(\"PredictedTransactionsCount\", \"TransactionsCount\"), 2) AS previsione\r\nFROM stats;"
    },
    {
     "rawSql": "WITH stats AS (\r\n  SELECT\r\n    \"PredictedTransactionsCount\", \"TransactionsCount\"\r\n  FROM \"PredictedTransactionsCount\" ptc\r\n  JOIN \"TransactionsCount\" tc ON tc.\"User_Name\" = ptc.\"User_Name\" AND tc.\"Date\" = ptc.\"Date\"\r\n  WHERE\r\n  ($SelectedClienti='*' OR\r\n    ptc.\"User_Name\"=$SelectedClienti) AND\r\n    ptc.\"PredictedTransactionsCount\" != 0 AND\r\n    tc.\"TransactionsCount\" != 0 AND\r\n    ptc.\"IsAfterRetrain\" = TRUE AND\r\n  $__timeFilter(ptc.\"Date\")\r\n)\r\nSELECT\r\n  POWER(CORR(\"PredictedTransactionsCount\", \"TransactionsCount\"), 2) AS previsione\r\nFROM stats;"
    }
   ]
  },
  { "title": "Distribuzione per tipo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Accessi per tipo (CIE/SPID)",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Type.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "Count", "id": "1", "type": "max" }
     ],
     "query": "_index:count-by-type",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Accessi per livello (L2/L3)",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Response_Assertion_AuthnContextClassRef.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "Count", "id": "1", "type": "max" }
     ],
     "query": "_index:count-by-class-ref",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Accessi per IdP",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 9, "x": 8, "y": 19 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "prefix.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "Count", "id": "1", "type": "max" }
     ],
     "query": "_index:count-by-idp",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Accessi per Utente",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "User_name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "Count", "id": "1", "type": "max" }
     ],
     "query": "_index:count-by-type",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Accessi per tipo (PUB/PRI)",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "InstanceType.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "Count", "id": "1", "type": "max" }
     ],
     "query": "_index:count-by-instance-type",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Accessi per attributi (std/min/full)",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "AttrSet.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "Count", "id": "1", "type": "max" }
     ],
     "query": "_index:count-by-attr-set",
     "timeField": "created_at"
    }
   ]
  },
  { "title": "Distribuzione temporale", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Distribuzione accessi nella giornata",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "WITH hours AS (\r\n    SELECT generate_series(0, 23) AS hour\r\n),\r\nhourly_counts AS (\r\n    SELECT \r\n        EXTRACT(HOUR FROM \"Date\") AS ora,\r\n        SUM(\"TransactionsCount\") AS count\r\n    FROM \r\n        \"TransactionsCount\"\r\n    WHERE \r\n        $__timeFilter(\"Date\") AND\r\n        ($SelectedClienti='*' OR \"User_Name\"=$SelectedClienti)\r\n    GROUP BY ora\r\n)\r\nSELECT \r\n    h.hour AS ora,\r\n    COALESCE(hc.count, 0) AS count\r\nFROM hours h\r\nLEFT JOIN hourly_counts hc\r\nON h.hour = hc.ora\r\nORDER BY h.hour;"
    }
   ]
  },
  {
   "title": "Distribuzione accessi nell'anno",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 10, "x": 9, "y": 32 },
   "targets": [
    {
     "rawSql": "WITH months AS (\r\n    SELECT generate_series(1, 12) AS month\r\n),\r\nmonthly_counts AS (\r\n    SELECT \r\n        EXTRACT(MONTH FROM \"Date\") AS month,\r\n        SUM(\"TransactionsCount\") AS count\r\n    FROM \r\n        \"TransactionsCount\"\r\n    WHERE\r\n        ($SelectedClienti='*' OR \"User_Name\"=$SelectedClienti)\r\n    GROUP BY month\r\n)\r\nSELECT \r\n    TO_CHAR(TO_DATE(m.month::TEXT, 'MM'), 'Month') AS month_name,\r\n    COALESCE(mc.count, 0) AS count\r\nFROM months m\r\nLEFT JOIN monthly_counts mc\r\nON m.month = mc.month\r\nORDER BY m.month;"
    }
   ]
  },
  {
   "title": "Distribuzione accessi per anno",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    EXTRACT(YEAR FROM \"Date\") AS year,\r\n    SUM(\"TransactionsCount\") AS count\r\nFROM \r\n    \"TransactionsCount\"\r\nWHERE ($SelectedClienti='*' OR \"User_Name\"=$SelectedClienti)\r\nGROUP BY year\r\nORDER BY year ASC"
    }
   ]
  }
 ]
}